object GameConfig {
    const val FRAME_WIDTH = 800
    const val FRAME_HEIGHT = 600
    const val FRAME_UPDATE_INTERVAL = 16
    const val PLAYER_SHIP_SHOOTING_INTERVAL = 200
    const val PLAYER_SHIP_PROJECTILE_MOVEMENT_INTERVAL = 20
    const val PLAYER_SHIP_WIDTH = 50
    const val PLAYER_SHIP_HEIGHT = 50
    const val PLAYER_SHIP_BULLET_WIDTH = 6
    const val PLAYER_SHIP_BULLET_HEIGHT = 2
    const val PLAYER_SHIP_SPEED = 4
    const val PLAYER_SHIP_PROJECTILE_SPEED = 1

    const val ENEMY_SHIP_SHOOTING_INTERVAL = 200
    const val ENEMY_SHIP_PROJECTILE_MOVEMENT_INTERVAL = 20
    const val ENEMY_SHIP_WIDTH = 50
    const val ENEMY_SHIP_HEIGHT = 50
    const val ENEMY_SHIP_BULLET_WIDTH = 6
    const val ENEMY_SHIP_BULLET_HEIGHT = 2
    const val ENEMY_SHIP_SPEED = 4
    const val ENEMY_SHIP_MOVEMENT_INTERVAL = 1000
    const val ENEMY_SHIP_PROJECTILE_SPEED = 1
    const val FPS = 60
    const val GAME_REDRAW_INTERVAL = 1000000 / FPS
}